name: ProxyIP地址维护

on:
  schedule:
    - cron: '30 23 * * *' # 中国的标准时间是UTC+8，因此早上7点半对应的UTC时间是23:30
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 安装 curl 和 jq
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: 加载当前的 GitHub 库
      uses: actions/checkout@v2

    - name: 执行脚本
      run: |
        chmod +x CFIPlus.sh
        ./CFIPlus.sh

    - name: 检查并同步文件
      run: |
        cd ip
        ls -al
        if [ -f "IPlus.txt" ] ; then
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add IPlus.txt US.txt
          git commit -m "Update files"
          git push https://${{ secrets.GH_TOKEN }}@github.com/ydl898898/CloudFlareIPlus.git
        else
          echo "IPlus.txt 文件不存在。跳过工作流程。"
          exit 0
        fi

    - name: 上传 DE-443.txt 和 US-443.txt
      run: |
        if [ -f "DE-443.txt" ] && [ -f "US-443.txt" ]; then
          git add DE-443.txt US-443.txt
          git commit -m "Upload DE-443.txt and US-443.txt"
          git push https://${{ secrets.GH_TOKEN }}@github.com/ydl898898/CloudFlareIPlus.git
        else
          echo "DE-443.txt 或 US-443.txt 文件不存在。跳过上传。"
        fi
