name: ProxyIP地址维护

on:
  #schedule:
  #  - cron: '30 23 * * *' # 中国的标准时间是UTC+8，因此早上7点半对应的UTC时间是23:30
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 安装 curl 和 jq
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: 加载当前的 GitHub 库
      uses: actions/checkout@v2

    - name: 执行脚本
      run: |
        chmod +x CFIPlus.sh
        ./CFIPlus.sh

    - name: 检查并同步文件
      run: |
        cd ip
        ls -al *.txt  # 确认当前目录下包含需要上传的 .txt 文件
        if [ -n "$(ls -A *.txt)" ]; then
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add *.txt
          git commit -m "更新 txt files"
          git push https://${{ secrets.GH_TOKEN }}@github.com/ydl898898/CloudFlareIPlus.git
        else
         echo "没有找到 .txt 文件。跳过上传。"
        fi
